/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicamentos.interfaces;

import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import medicamentos.dao.DAOLaboratorio;
import medicamentos.dao.DAOMedicamento;
import medicamentos.entidades.Laboratorio;
import medicamentos.entidades.Medicamento;

/**
 *
 * @author AULA EPG 23
 */
public class JFMedicamento extends javax.swing.JFrame {

    private MedicamentoTableModel medicamentoTable = new MedicamentoTableModel();
    private Medicamento actual;
    private List<Medicamento> medicamentos;
    private List<Laboratorio> laboratorios;

    /**
     * Creates new form JFMedicamento
     */
    public JFMedicamento() {
        initComponents();
        this.activarControles(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMedicamento = new javax.swing.JPanel();
        lblLaboratorio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        chkVigente = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        cboLaboratorio = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        spPrecio = new javax.swing.JSpinner();
        btnCerrar = new javax.swing.JButton();
        panListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblMedicamento = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnPrincipios = new javax.swing.JButton();
        btnImportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicamento"));

        lblLaboratorio.setText("Laboratorio");

        chkVigente.setText("Vigente");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        cboLaboratorio.setModel(listarLaboratorios());

        lblPrecio.setText("Precio");

        spPrecio.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, null, 1.0d));

        javax.swing.GroupLayout panMedicamentoLayout = new javax.swing.GroupLayout(panMedicamento);
        panMedicamento.setLayout(panMedicamentoLayout);
        panMedicamentoLayout.setHorizontalGroup(
            panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMedicamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMedicamentoLayout.createSequentialGroup()
                        .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblLaboratorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(cboLaboratorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panMedicamentoLayout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(42, 42, 42)
                        .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkVigente)
                            .addComponent(spPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panMedicamentoLayout.setVerticalGroup(
            panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMedicamentoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLaboratorio)
                    .addComponent(cboLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(25, 25, 25)
                .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(spPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkVigente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        panListado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Listado"));

        tblListado.setModel( this.medicamentoTable);
        tblListado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblListado);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lblMedicamento.setText("Medicamento");

        txtMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicamentoActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnPrincipios.setText("Principios");
        btnPrincipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipiosActionPerformed(evt);
            }
        });

        btnImportar.setText("Importar principios");

        javax.swing.GroupLayout panListadoLayout = new javax.swing.GroupLayout(panListado);
        panListado.setLayout(panListadoLayout);
        panListadoLayout.setHorizontalGroup(
            panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panListadoLayout.createSequentialGroup()
                        .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panListadoLayout.createSequentialGroup()
                                .addComponent(lblMedicamento)
                                .addGap(18, 18, 18)
                                .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar))
                            .addGroup(panListadoLayout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrincipios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImportar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panListadoLayout.setVerticalGroup(
            panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicamento)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnPrincipios)
                    .addComponent(btnImportar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Medicamento med;
        DAOMedicamento dao;

        if (this.validar() == true) {
            med = this.crearEntidad();
            dao = new DAOMedicamento();
            try {
                if (this.actual == null) {
                    dao.registrar(med);
                } else {
                    dao.modificar(med);
                }
                this.activarControles(false);
                this.limpiarControles();           
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private Medicamento crearEntidad() {
        Medicamento med = new Medicamento();

        med.setLaboratorio(this.laboratorios.get(this.cboLaboratorio.getSelectedIndex()));
        med.setNombre(this.txtNombre.getText());
        med.setPrecio( Double.parseDouble( this.spPrecio.getValue().toString()));
        med.setVigente( this.chkVigente.isSelected());
        if( this.actual != null){
            med.setCodigo(this.actual.getCodigo());
        }
        
        return med;
    }

    private boolean validar() {
        return true;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.activarControles(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.activarControles(true);
        this.limpiarControles();
        this.actual = null;
        this.chkVigente.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila = this.tblListado.getSelectedRow();

        if (fila > -1) {
            this.actual = this.medicamentos.get(fila);
            this.presentarDatos();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un laboratorio");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        DAOMedicamento dao = new DAOMedicamento();

        try {
            this.medicamentos = dao.listar(this.txtMedicamento.getText());
            this.medicamentoTable.setMedicamentos(this.medicamentos);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo listar los laboratorios");
        }    }//GEN-LAST:event_btnListarActionPerformed

    private void btnPrincipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipiosActionPerformed
        JFAddPrincipios frame = new JFAddPrincipios();
        frame.setVisible(true);
    }//GEN-LAST:event_btnPrincipiosActionPerformed

    private void txtMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrincipios;
    private javax.swing.JComboBox<String> cboLaboratorio;
    private javax.swing.JCheckBox chkVigente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel panListado;
    private javax.swing.JPanel panMedicamento;
    private javax.swing.JSpinner spPrecio;
    private javax.swing.JTable tblListado;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void presentarDatos() {
        DAOMedicamento dao = new DAOMedicamento();
        ComboBoxModel modeloCombo;
        
        try{
            this.actual = dao.leer(this.actual.getCodigo());
            if( this.actual != null){
                modeloCombo = this.cboLaboratorio.getModel();
                ((LaboratorioComboBoxModel)modeloCombo).seleccionar( this.actual.getLaboratorio());
                this.txtNombre.setText(this.actual.getNombre());
                this.spPrecio.setValue(this.actual.getPrecio());
                this.chkVigente.setSelected(this.actual.isVigente());
                this.activarControles(true);
            }else{
                JOptionPane.showMessageDialog(this, "No se encontró el medicamento");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se pudo obtener la informaciòn del medicamento");
        }
    }

    private void activarControles(boolean estado) {
        this.panMedicamento.setEnabled(estado);
        this.lblLaboratorio.setEnabled(estado);
        this.cboLaboratorio.setEnabled(estado);
        this.lblNombre.setEnabled(estado);
        this.txtNombre.setEnabled(estado);
        this.lblPrecio.setEnabled(estado);
        this.spPrecio.setEnabled(estado);
        this.chkVigente.setEnabled(estado);

        this.panListado.setEnabled(!estado);
        this.lblMedicamento.setEnabled(!estado);
        this.txtMedicamento.setEnabled(!estado);
        this.btnListar.setEnabled(!estado);
        this.tblListado.setEnabled(!estado);
        this.btnNuevo.setEnabled(!estado);
        this.btnModificar.setEnabled(!estado);
        if (estado == true) {
            this.cboLaboratorio.requestFocusInWindow();
        } else {
            this.txtMedicamento.requestFocusInWindow();
        }
    }

    private void limpiarControles() {
        this.cboLaboratorio.setSelectedIndex(-1);
        this.txtNombre.setText("");
        this.spPrecio.setValue(1.0);
        this.chkVigente.setSelected(true);
    }

    private ComboBoxModel listarLaboratorios() {
        LaboratorioComboBoxModel modelo = new LaboratorioComboBoxModel();

        modelo.setLaboratorios(this.listarLaboratoriosVigentes());

        return modelo;
    }

    private List<Laboratorio> listarLaboratoriosVigentes() {
        DAOLaboratorio dao = new DAOLaboratorio();

        try {
            this.laboratorios = dao.listarVigentes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo obtener la lista de laboratorios");
        }

        return this.laboratorios;
    }
}
