/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicamentos.interfaces;

import java.util.List;
import javax.swing.JOptionPane;
import medicamentos.entidades.PrincipioActivo;
import medicamentos.dao.DAOPrincipioActivo;

/**
 *
 * @author Jose Guevara
 */
public class JFPrincipioActivo extends javax.swing.JFrame {

    private List<PrincipioActivo> principiosActivos;
    private PrincipioActivo actual;
    private PrincipioActivoTableModel principioTable = new PrincipioActivoTableModel();
    
    /**
     * Creates new form JFPrincipioActivo
     */
    public JFPrincipioActivo() {
        initComponents();
        this.activarControles(false);
        this.listarPrincipiosActivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipioActivo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        chkVigente = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        panListadoPA = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoPA = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panPrincipioActivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Principio Activo"));

        lblNombre.setText("Nombre:");

        lblDescripcion.setText("Descripción:");

        chkVigente.setText("Vigente");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPrincipioActivoLayout = new javax.swing.GroupLayout(panPrincipioActivo);
        panPrincipioActivo.setLayout(panPrincipioActivoLayout);
        panPrincipioActivoLayout.setHorizontalGroup(
            panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipioActivoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(chkVigente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panPrincipioActivoLayout.createSequentialGroup()
                .addGroup(panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipioActivoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescripcion)
                            .addComponent(lblNombre))
                        .addGap(18, 18, 18)
                        .addGroup(panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtDescripcion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipioActivoLayout.createSequentialGroup()
                        .addContainerGap(113, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        panPrincipioActivoLayout.setVerticalGroup(
            panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipioActivoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkVigente)
                .addGap(18, 18, 18)
                .addGroup(panPrincipioActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panListadoPA.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tblListadoPA.setModel(this.principioTable);
        jScrollPane1.setViewportView(tblListadoPA);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panListadoPALayout = new javax.swing.GroupLayout(panListadoPA);
        panListadoPA.setLayout(panListadoPALayout);
        panListadoPALayout.setHorizontalGroup(
            panListadoPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListadoPALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panListadoPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panListadoPALayout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panListadoPALayout.setVerticalGroup(
            panListadoPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListadoPALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panListadoPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panListadoPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panPrincipioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panListadoPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.activarControles(true);
        this.limpiarControles();
        this.actual = null;
        this.txtNombre.requestFocusInWindow();
        this.txtDescripcion.requestFocusInWindow();
        this.chkVigente.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.activarControles(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        PrincipioActivo pAct;
        DAOPrincipioActivo dao;
        
        if( this.validar() == true){
            pAct = this.crearEntidad();
            dao = new DAOPrincipioActivo();
            try{
                if( this.actual==null){
                    dao.registrar(pAct);
                }else{
                    dao.modificar(pAct);
                }
                this.listarPrincipiosActivos();
                this.activarControles(false);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila = this.tblListadoPA.getSelectedRow();
        
        if( fila> -1){
            this.actual = this.principiosActivos.get(fila);
            this.presentarDatos();
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Principio Activo");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipioActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipioActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipioActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipioActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipioActivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkVigente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panListadoPA;
    private javax.swing.JPanel panPrincipioActivo;
    private javax.swing.JTable tblListadoPA;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void activarControles(boolean estado) {
        this.panPrincipioActivo.setEnabled(estado);
        this.lblNombre.setEnabled(estado);
        this.txtNombre.setEditable(estado);
        this.lblDescripcion.setEnabled(estado);
        this.txtDescripcion.setEditable(estado);
        this.chkVigente.setEnabled(estado);
        this.btnAceptar.setEnabled(estado);
        this.btnCancelar.setEnabled(estado);
        
        this.panListadoPA.setEnabled(! estado);
        this.tblListadoPA.setEnabled(! estado);
        this.btnNuevo.setEnabled(! estado);
        this.btnModificar.setEnabled(! estado);
        
        if(estado == true){
            this.txtNombre.requestFocusInWindow();
        }else{
            this.tblListadoPA.requestFocusInWindow();
        }
    }

    private void listarPrincipiosActivos() {
        DAOPrincipioActivo dao = new DAOPrincipioActivo();
        
        try {
            this.principiosActivos = dao.listar();
            this.principioTable.setPrincipiosActivos(principiosActivos);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo listar los Principios Activos");
        }
    }

    private void limpiarControles() {
        this.txtNombre.setText("");
        this.txtDescripcion.setText("");
        this.chkVigente.setSelected(true);
    }

    private boolean validar() {
        return true;
    }

    private PrincipioActivo crearEntidad() {
        PrincipioActivo pAct =new PrincipioActivo();
        
        pAct.setNombre(this.txtNombre.getText());
        pAct.setDescripcion(this.txtDescripcion.getText());
        pAct.setVigente(this.chkVigente.isSelected());
        if( this.actual  != null){
            pAct.setCodigo(this.actual.getCodigo());
        }
        return pAct;
    }

    private void presentarDatos() {
        this.activarControles(true);
        this.txtNombre.setText(this.actual.getNombre());
        this.txtDescripcion.setText(this.actual.getDescripcion());
        this.chkVigente.setSelected(this.actual .isVigente());
    }
}
